"""add news_articles

Revision ID: 4aefd0e1347e
Revises: d675f5306a2a
Create Date: 2026-02-17 02:39:43.799094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4aefd0e1347e'
down_revision: Union[str, Sequence[str], None] = 'd675f5306a2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(length=32), server_default='gdelt_bigquery', nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'url', name='uq_news_symbol_url')
    )
    op.create_index(op.f('ix_news_articles_day'), 'news_articles', ['day'], unique=False)
    op.create_index(op.f('ix_news_articles_symbol_id'), 'news_articles', ['symbol_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_articles_symbol_id'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_day'), table_name='news_articles')
    op.drop_table('news_articles')
    # ### end Alembic commands ###
