"""recreate bars table

Revision ID: 6402c298d289
Revises: 414ac7be9652
Create Date: 2026-02-14 22:24:52.244750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6402c298d289'
down_revision: Union[str, Sequence[str], None] = '414ac7be9652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('provider', sa.String(length=16), server_default='massive', nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'timeframe', 'ts', name='uq_bars_symbol_tf_ts')
    )
    op.create_index(op.f('ix_bars_id'), 'bars', ['id'], unique=False)
    op.create_index(op.f('ix_bars_symbol_id'), 'bars', ['symbol_id'], unique=False)
    op.create_index(op.f('ix_bars_timeframe'), 'bars', ['timeframe'], unique=False)
    op.create_index(op.f('ix_bars_ts'), 'bars', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bars_ts'), table_name='bars')
    op.drop_index(op.f('ix_bars_timeframe'), table_name='bars')
    op.drop_index(op.f('ix_bars_symbol_id'), table_name='bars')
    op.drop_index(op.f('ix_bars_id'), table_name='bars')
    op.drop_table('bars')
    # ### end Alembic commands ###
