"""add symbol metadata columns

Revision ID: d675f5306a2a
Revises: f1c7fcad138b
Create Date: 2026-02-15 15:57:54.814511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd675f5306a2a'
down_revision: Union[str, Sequence[str], None] = 'f1c7fcad138b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symbols', sa.Column('name', sa.String(length=128), nullable=True))
    op.add_column('symbols', sa.Column('exchange', sa.String(length=32), nullable=True))
    op.add_column('symbols', sa.Column('country', sa.String(length=8), nullable=True))
    op.add_column('symbols', sa.Column('currency', sa.String(length=8), nullable=True))
    op.add_column('symbols', sa.Column('mic', sa.String(length=16), nullable=True))
    op.add_column('symbols', sa.Column('type', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symbols', 'type')
    op.drop_column('symbols', 'mic')
    op.drop_column('symbols', 'currency')
    op.drop_column('symbols', 'country')
    op.drop_column('symbols', 'exchange')
    op.drop_column('symbols', 'name')
    # ### end Alembic commands ###
